---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-client
spec:
  template:
    spec:
      containers:
      - name: hello-service-client
        env:
        - name: service_a_host
          value: "hello-service-a"
        - name: service_a_port
          value: "30185"
        - name: env
          value: "dev"